production:
  database: production

development:
  database: development

test:
  # for some reason, test doesn't use the env variable automatically anymore
  url: <%= ENV['DATABASE_URL'] %>
  database: test
